name: App-Multi Build

on:
    workflow_call:
      inputs:
          env:
            required: true
            type: string

permissions:
  packages: write
  contents: read

jobs:
  build-app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Move source
        run: |
            mkdir -p deploy/context
            cp app-multi/*.js deploy/context
            cp app-multi/*.json deploy/context
            cp deploy/containers/app-multi/* deploy/context
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor}}
          password: ${{ github.token }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: deploy/context
          # replace tiptenbrink with your organization name or GitHub username (i.e. the parent name of your repo)
          tags: ghcr.io/tiptenbrink/hellodeploy-app-multi:${{ inputs.env }}
          cache-from: type=gha
          cache-to: type=gha, mode=max
          push: true
