name: Server Build

on:
    workflow_call:
      inputs:
          env:
            required: true
            type: string

permissions:
  packages: write
  contents: read

jobs:
  build-server:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Move source
        run: |
            mkdir -p deploy/context
            cp app/*.js deploy/context
            cp app/*.json deploy/context
            cp deploy/containers/app/* deploy/context
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          # We use the repo/action token, which has specified access to the package
          username: ${{ github.actor}}
          password: ${{ github.token }}
      # Build and push
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: deploy/context
          tags: ghcr.io/tiptenbrink/hellodeploy-app:${{ inputs.env }}
          cache-from: type=gha
          cache-to: type=gha, mode=max
          push: true

