name: CI

on:
  push:
    branches: [ main ]

permissions:
  packages: write
  contents: write

jobs:
  build-app:
    strategy:
      matrix:
        target: [ 'production' ]
    uses: tiptenbrink/hellodeploy/.github/workflows/app.yml@main
    with:
      env: ${{ matrix.target }}
