name: CI

on:
  push:
    branches: [ main ]

permissions:
  packages: write
  contents: write

jobs:
  build-app:
    strategy:
      matrix:
        target: [ 'production' ]
    # replace tiptenbrink/hellodeploy with your own repository 
    uses: tiptenbrink/hellodeploy/.github/workflows/app.yml@main
    with:
      env: ${{ matrix.target }}
  build-deployer:
    # replace tiptenbrink/hellodeploy with your own repository 
    uses: tiptenbrink/hellodeploy/.github/workflows/deployer.yml@main
